version: '3.1'

services:

  app-fe:
    image: app-fe:1.2
    ports:
      - 8080:80
    depends_on:
    - app-be

  app-be:
    image: app-be:1.2
    # ports:
    #   - 9080:9080
    environment:
      MONGO_CONN_STR: mongodb://mongo:27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - mongo
    networks:
      - mongo_net


  mongo:
    image: mongo:1.2
    restart: always
    networks:
      mongo_net:
        ipv4_address: 172.16.0.1
    command: mongod --bind_ip 127.0.0.1,172.16.0.1
    environment:
      MONGO_CONN_STR: mongodb://172.16.0.1:27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017


networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.254

# networks:
#   default:
#     name: app_net
#     external: true