FROM node:12-alpine as BUILD

WORKDIR /app
COPY . .

RUN npm install --production 
RUN ls -la /app/conf.d

FROM nginx:stable-alpine
COPY --from=build /app/public/ /usr/share/nginx/html
COPY --from=build /app/env.sh /docker-entrypoint.d
COPY conf.d/default.conf /etc/nginx/conf.

